package com.qsy.demo.oa.pojo;

public class GoodsInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.GOODS_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.GOODS_NAME
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.GOODS_DESC
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private String goodsDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.GOODS_IMAGE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private String goodsImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.GOODS_COUNT
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private Integer goodsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.GOODS_PRICE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private Double goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.GOODS_STATE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private String goodsState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.GOODS_ID
     *
     * @return the value of goods_info.GOODS_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.GOODS_ID
     *
     * @param goodsId the value for goods_info.GOODS_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.GOODS_NAME
     *
     * @return the value of goods_info.GOODS_NAME
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.GOODS_NAME
     *
     * @param goodsName the value for goods_info.GOODS_NAME
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.GOODS_DESC
     *
     * @return the value of goods_info.GOODS_DESC
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public String getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.GOODS_DESC
     *
     * @param goodsDesc the value for goods_info.GOODS_DESC
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc == null ? null : goodsDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.GOODS_IMAGE
     *
     * @return the value of goods_info.GOODS_IMAGE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public String getGoodsImage() {
        return goodsImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.GOODS_IMAGE
     *
     * @param goodsImage the value for goods_info.GOODS_IMAGE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setGoodsImage(String goodsImage) {
        this.goodsImage = goodsImage == null ? null : goodsImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.GOODS_COUNT
     *
     * @return the value of goods_info.GOODS_COUNT
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.GOODS_COUNT
     *
     * @param goodsCount the value for goods_info.GOODS_COUNT
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.GOODS_PRICE
     *
     * @return the value of goods_info.GOODS_PRICE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.GOODS_PRICE
     *
     * @param goodsPrice the value for goods_info.GOODS_PRICE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.GOODS_STATE
     *
     * @return the value of goods_info.GOODS_STATE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public String getGoodsState() {
        return goodsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.GOODS_STATE
     *
     * @param goodsState the value for goods_info.GOODS_STATE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setGoodsState(String goodsState) {
        this.goodsState = goodsState == null ? null : goodsState.trim();
    }
}