package com.qsy.demo.oa.pojo;

public class GoodsSortRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sort_relation.GOODS_SORT_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private Integer goodsSortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sort_relation.GOODS_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sort_relation.SORT_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private Integer sortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sort_relation.GOODS_SORT_STATE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private String goodsSortState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_sort_relation.GOODS_SORT_ID
     *
     * @return the value of goods_sort_relation.GOODS_SORT_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Integer getGoodsSortId() {
        return goodsSortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_sort_relation.GOODS_SORT_ID
     *
     * @param goodsSortId the value for goods_sort_relation.GOODS_SORT_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setGoodsSortId(Integer goodsSortId) {
        this.goodsSortId = goodsSortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_sort_relation.GOODS_ID
     *
     * @return the value of goods_sort_relation.GOODS_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_sort_relation.GOODS_ID
     *
     * @param goodsId the value for goods_sort_relation.GOODS_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_sort_relation.SORT_ID
     *
     * @return the value of goods_sort_relation.SORT_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_sort_relation.SORT_ID
     *
     * @param sortId the value for goods_sort_relation.SORT_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_sort_relation.GOODS_SORT_STATE
     *
     * @return the value of goods_sort_relation.GOODS_SORT_STATE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public String getGoodsSortState() {
        return goodsSortState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_sort_relation.GOODS_SORT_STATE
     *
     * @param goodsSortState the value for goods_sort_relation.GOODS_SORT_STATE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setGoodsSortState(String goodsSortState) {
        this.goodsSortState = goodsSortState == null ? null : goodsSortState.trim();
    }
}