package com.qsy.demo.oa.pojo;

import java.util.ArrayList;
import java.util.List;

public class GoodsSortRelationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public GoodsSortRelationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGoodsSortIdIsNull() {
            addCriterion("GOODS_SORT_ID is null");
            return (Criteria) this;
        }

        public Criteria andGoodsSortIdIsNotNull() {
            addCriterion("GOODS_SORT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsSortIdEqualTo(Integer value) {
            addCriterion("GOODS_SORT_ID =", value, "goodsSortId");
            return (Criteria) this;
        }

        public Criteria andGoodsSortIdNotEqualTo(Integer value) {
            addCriterion("GOODS_SORT_ID <>", value, "goodsSortId");
            return (Criteria) this;
        }

        public Criteria andGoodsSortIdGreaterThan(Integer value) {
            addCriterion("GOODS_SORT_ID >", value, "goodsSortId");
            return (Criteria) this;
        }

        public Criteria andGoodsSortIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("GOODS_SORT_ID >=", value, "goodsSortId");
            return (Criteria) this;
        }

        public Criteria andGoodsSortIdLessThan(Integer value) {
            addCriterion("GOODS_SORT_ID <", value, "goodsSortId");
            return (Criteria) this;
        }

        public Criteria andGoodsSortIdLessThanOrEqualTo(Integer value) {
            addCriterion("GOODS_SORT_ID <=", value, "goodsSortId");
            return (Criteria) this;
        }

        public Criteria andGoodsSortIdIn(List<Integer> values) {
            addCriterion("GOODS_SORT_ID in", values, "goodsSortId");
            return (Criteria) this;
        }

        public Criteria andGoodsSortIdNotIn(List<Integer> values) {
            addCriterion("GOODS_SORT_ID not in", values, "goodsSortId");
            return (Criteria) this;
        }

        public Criteria andGoodsSortIdBetween(Integer value1, Integer value2) {
            addCriterion("GOODS_SORT_ID between", value1, value2, "goodsSortId");
            return (Criteria) this;
        }

        public Criteria andGoodsSortIdNotBetween(Integer value1, Integer value2) {
            addCriterion("GOODS_SORT_ID not between", value1, value2, "goodsSortId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("GOODS_ID is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("GOODS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(Integer value) {
            addCriterion("GOODS_ID =", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(Integer value) {
            addCriterion("GOODS_ID <>", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(Integer value) {
            addCriterion("GOODS_ID >", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("GOODS_ID >=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(Integer value) {
            addCriterion("GOODS_ID <", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(Integer value) {
            addCriterion("GOODS_ID <=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<Integer> values) {
            addCriterion("GOODS_ID in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<Integer> values) {
            addCriterion("GOODS_ID not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(Integer value1, Integer value2) {
            addCriterion("GOODS_ID between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("GOODS_ID not between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andSortIdIsNull() {
            addCriterion("SORT_ID is null");
            return (Criteria) this;
        }

        public Criteria andSortIdIsNotNull() {
            addCriterion("SORT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSortIdEqualTo(Integer value) {
            addCriterion("SORT_ID =", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdNotEqualTo(Integer value) {
            addCriterion("SORT_ID <>", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdGreaterThan(Integer value) {
            addCriterion("SORT_ID >", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SORT_ID >=", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdLessThan(Integer value) {
            addCriterion("SORT_ID <", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdLessThanOrEqualTo(Integer value) {
            addCriterion("SORT_ID <=", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdIn(List<Integer> values) {
            addCriterion("SORT_ID in", values, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdNotIn(List<Integer> values) {
            addCriterion("SORT_ID not in", values, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdBetween(Integer value1, Integer value2) {
            addCriterion("SORT_ID between", value1, value2, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SORT_ID not between", value1, value2, "sortId");
            return (Criteria) this;
        }

        public Criteria andGoodsSortStateIsNull() {
            addCriterion("GOODS_SORT_STATE is null");
            return (Criteria) this;
        }

        public Criteria andGoodsSortStateIsNotNull() {
            addCriterion("GOODS_SORT_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsSortStateEqualTo(String value) {
            addCriterion("GOODS_SORT_STATE =", value, "goodsSortState");
            return (Criteria) this;
        }

        public Criteria andGoodsSortStateNotEqualTo(String value) {
            addCriterion("GOODS_SORT_STATE <>", value, "goodsSortState");
            return (Criteria) this;
        }

        public Criteria andGoodsSortStateGreaterThan(String value) {
            addCriterion("GOODS_SORT_STATE >", value, "goodsSortState");
            return (Criteria) this;
        }

        public Criteria andGoodsSortStateGreaterThanOrEqualTo(String value) {
            addCriterion("GOODS_SORT_STATE >=", value, "goodsSortState");
            return (Criteria) this;
        }

        public Criteria andGoodsSortStateLessThan(String value) {
            addCriterion("GOODS_SORT_STATE <", value, "goodsSortState");
            return (Criteria) this;
        }

        public Criteria andGoodsSortStateLessThanOrEqualTo(String value) {
            addCriterion("GOODS_SORT_STATE <=", value, "goodsSortState");
            return (Criteria) this;
        }

        public Criteria andGoodsSortStateLike(String value) {
            addCriterion("GOODS_SORT_STATE like", value, "goodsSortState");
            return (Criteria) this;
        }

        public Criteria andGoodsSortStateNotLike(String value) {
            addCriterion("GOODS_SORT_STATE not like", value, "goodsSortState");
            return (Criteria) this;
        }

        public Criteria andGoodsSortStateIn(List<String> values) {
            addCriterion("GOODS_SORT_STATE in", values, "goodsSortState");
            return (Criteria) this;
        }

        public Criteria andGoodsSortStateNotIn(List<String> values) {
            addCriterion("GOODS_SORT_STATE not in", values, "goodsSortState");
            return (Criteria) this;
        }

        public Criteria andGoodsSortStateBetween(String value1, String value2) {
            addCriterion("GOODS_SORT_STATE between", value1, value2, "goodsSortState");
            return (Criteria) this;
        }

        public Criteria andGoodsSortStateNotBetween(String value1, String value2) {
            addCriterion("GOODS_SORT_STATE not between", value1, value2, "goodsSortState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_sort_relation
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 17 17:17:22 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}