package com.qsy.demo.oa.pojo;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_NAME
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_TYPE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private String permissionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_URL
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private String permissionUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_PERCODE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private String permissionPercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_PARENTID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private Long permissionParentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_PARENTIDS
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private String permissionParentids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_SORTSTRING
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private String permissionSortstring;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_AVAILABLE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private String permissionAvailable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PERMISSION_ID
     *
     * @return the value of permission.PERMISSION_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PERMISSION_ID
     *
     * @param permissionId the value for permission.PERMISSION_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PERMISSION_NAME
     *
     * @return the value of permission.PERMISSION_NAME
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PERMISSION_NAME
     *
     * @param permissionName the value for permission.PERMISSION_NAME
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PERMISSION_TYPE
     *
     * @return the value of permission.PERMISSION_TYPE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public String getPermissionType() {
        return permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PERMISSION_TYPE
     *
     * @param permissionType the value for permission.PERMISSION_TYPE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setPermissionType(String permissionType) {
        this.permissionType = permissionType == null ? null : permissionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PERMISSION_URL
     *
     * @return the value of permission.PERMISSION_URL
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public String getPermissionUrl() {
        return permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PERMISSION_URL
     *
     * @param permissionUrl the value for permission.PERMISSION_URL
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setPermissionUrl(String permissionUrl) {
        this.permissionUrl = permissionUrl == null ? null : permissionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PERMISSION_PERCODE
     *
     * @return the value of permission.PERMISSION_PERCODE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public String getPermissionPercode() {
        return permissionPercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PERMISSION_PERCODE
     *
     * @param permissionPercode the value for permission.PERMISSION_PERCODE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setPermissionPercode(String permissionPercode) {
        this.permissionPercode = permissionPercode == null ? null : permissionPercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PERMISSION_PARENTID
     *
     * @return the value of permission.PERMISSION_PARENTID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Long getPermissionParentid() {
        return permissionParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PERMISSION_PARENTID
     *
     * @param permissionParentid the value for permission.PERMISSION_PARENTID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setPermissionParentid(Long permissionParentid) {
        this.permissionParentid = permissionParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PERMISSION_PARENTIDS
     *
     * @return the value of permission.PERMISSION_PARENTIDS
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public String getPermissionParentids() {
        return permissionParentids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PERMISSION_PARENTIDS
     *
     * @param permissionParentids the value for permission.PERMISSION_PARENTIDS
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setPermissionParentids(String permissionParentids) {
        this.permissionParentids = permissionParentids == null ? null : permissionParentids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PERMISSION_SORTSTRING
     *
     * @return the value of permission.PERMISSION_SORTSTRING
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public String getPermissionSortstring() {
        return permissionSortstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PERMISSION_SORTSTRING
     *
     * @param permissionSortstring the value for permission.PERMISSION_SORTSTRING
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setPermissionSortstring(String permissionSortstring) {
        this.permissionSortstring = permissionSortstring == null ? null : permissionSortstring.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PERMISSION_AVAILABLE
     *
     * @return the value of permission.PERMISSION_AVAILABLE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public String getPermissionAvailable() {
        return permissionAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PERMISSION_AVAILABLE
     *
     * @param permissionAvailable the value for permission.PERMISSION_AVAILABLE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setPermissionAvailable(String permissionAvailable) {
        this.permissionAvailable = permissionAvailable == null ? null : permissionAvailable.trim();
    }
}