package com.qsy.demo.oa.pojo;

import java.util.Date;

public class RolePermissionRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_relation.ROLE_PERMISSION_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private Integer rolePermissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_relation.ROLE_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_relation.PERMISSION
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private Integer permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_relation.ROLE_PERMISSION_STATE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private String rolePermissionState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_relation.ROLE_PERMISSION_UPDATETIME
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    private Date rolePermissionUpdatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_relation.ROLE_PERMISSION_ID
     *
     * @return the value of role_permission_relation.ROLE_PERMISSION_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Integer getRolePermissionId() {
        return rolePermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_relation.ROLE_PERMISSION_ID
     *
     * @param rolePermissionId the value for role_permission_relation.ROLE_PERMISSION_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setRolePermissionId(Integer rolePermissionId) {
        this.rolePermissionId = rolePermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_relation.ROLE_ID
     *
     * @return the value of role_permission_relation.ROLE_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_relation.ROLE_ID
     *
     * @param roleId the value for role_permission_relation.ROLE_ID
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_relation.PERMISSION
     *
     * @return the value of role_permission_relation.PERMISSION
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Integer getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_relation.PERMISSION
     *
     * @param permission the value for role_permission_relation.PERMISSION
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setPermission(Integer permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_relation.ROLE_PERMISSION_STATE
     *
     * @return the value of role_permission_relation.ROLE_PERMISSION_STATE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public String getRolePermissionState() {
        return rolePermissionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_relation.ROLE_PERMISSION_STATE
     *
     * @param rolePermissionState the value for role_permission_relation.ROLE_PERMISSION_STATE
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setRolePermissionState(String rolePermissionState) {
        this.rolePermissionState = rolePermissionState == null ? null : rolePermissionState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_relation.ROLE_PERMISSION_UPDATETIME
     *
     * @return the value of role_permission_relation.ROLE_PERMISSION_UPDATETIME
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Date getRolePermissionUpdatetime() {
        return rolePermissionUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_relation.ROLE_PERMISSION_UPDATETIME
     *
     * @param rolePermissionUpdatetime the value for role_permission_relation.ROLE_PERMISSION_UPDATETIME
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setRolePermissionUpdatetime(Date rolePermissionUpdatetime) {
        this.rolePermissionUpdatetime = rolePermissionUpdatetime;
    }
}