package com.qsy.demo.oa.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RolePermissionRelationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public RolePermissionRelationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRolePermissionIdIsNull() {
            addCriterion("ROLE_PERMISSION_ID is null");
            return (Criteria) this;
        }

        public Criteria andRolePermissionIdIsNotNull() {
            addCriterion("ROLE_PERMISSION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRolePermissionIdEqualTo(Integer value) {
            addCriterion("ROLE_PERMISSION_ID =", value, "rolePermissionId");
            return (Criteria) this;
        }

        public Criteria andRolePermissionIdNotEqualTo(Integer value) {
            addCriterion("ROLE_PERMISSION_ID <>", value, "rolePermissionId");
            return (Criteria) this;
        }

        public Criteria andRolePermissionIdGreaterThan(Integer value) {
            addCriterion("ROLE_PERMISSION_ID >", value, "rolePermissionId");
            return (Criteria) this;
        }

        public Criteria andRolePermissionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ROLE_PERMISSION_ID >=", value, "rolePermissionId");
            return (Criteria) this;
        }

        public Criteria andRolePermissionIdLessThan(Integer value) {
            addCriterion("ROLE_PERMISSION_ID <", value, "rolePermissionId");
            return (Criteria) this;
        }

        public Criteria andRolePermissionIdLessThanOrEqualTo(Integer value) {
            addCriterion("ROLE_PERMISSION_ID <=", value, "rolePermissionId");
            return (Criteria) this;
        }

        public Criteria andRolePermissionIdIn(List<Integer> values) {
            addCriterion("ROLE_PERMISSION_ID in", values, "rolePermissionId");
            return (Criteria) this;
        }

        public Criteria andRolePermissionIdNotIn(List<Integer> values) {
            addCriterion("ROLE_PERMISSION_ID not in", values, "rolePermissionId");
            return (Criteria) this;
        }

        public Criteria andRolePermissionIdBetween(Integer value1, Integer value2) {
            addCriterion("ROLE_PERMISSION_ID between", value1, value2, "rolePermissionId");
            return (Criteria) this;
        }

        public Criteria andRolePermissionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ROLE_PERMISSION_ID not between", value1, value2, "rolePermissionId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("ROLE_ID is null");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("ROLE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRoleIdEqualTo(Integer value) {
            addCriterion("ROLE_ID =", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotEqualTo(Integer value) {
            addCriterion("ROLE_ID <>", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThan(Integer value) {
            addCriterion("ROLE_ID >", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ROLE_ID >=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThan(Integer value) {
            addCriterion("ROLE_ID <", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(Integer value) {
            addCriterion("ROLE_ID <=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIn(List<Integer> values) {
            addCriterion("ROLE_ID in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotIn(List<Integer> values) {
            addCriterion("ROLE_ID not in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdBetween(Integer value1, Integer value2) {
            addCriterion("ROLE_ID between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ROLE_ID not between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andPermissionIsNull() {
            addCriterion("PERMISSION is null");
            return (Criteria) this;
        }

        public Criteria andPermissionIsNotNull() {
            addCriterion("PERMISSION is not null");
            return (Criteria) this;
        }

        public Criteria andPermissionEqualTo(Integer value) {
            addCriterion("PERMISSION =", value, "permission");
            return (Criteria) this;
        }

        public Criteria andPermissionNotEqualTo(Integer value) {
            addCriterion("PERMISSION <>", value, "permission");
            return (Criteria) this;
        }

        public Criteria andPermissionGreaterThan(Integer value) {
            addCriterion("PERMISSION >", value, "permission");
            return (Criteria) this;
        }

        public Criteria andPermissionGreaterThanOrEqualTo(Integer value) {
            addCriterion("PERMISSION >=", value, "permission");
            return (Criteria) this;
        }

        public Criteria andPermissionLessThan(Integer value) {
            addCriterion("PERMISSION <", value, "permission");
            return (Criteria) this;
        }

        public Criteria andPermissionLessThanOrEqualTo(Integer value) {
            addCriterion("PERMISSION <=", value, "permission");
            return (Criteria) this;
        }

        public Criteria andPermissionIn(List<Integer> values) {
            addCriterion("PERMISSION in", values, "permission");
            return (Criteria) this;
        }

        public Criteria andPermissionNotIn(List<Integer> values) {
            addCriterion("PERMISSION not in", values, "permission");
            return (Criteria) this;
        }

        public Criteria andPermissionBetween(Integer value1, Integer value2) {
            addCriterion("PERMISSION between", value1, value2, "permission");
            return (Criteria) this;
        }

        public Criteria andPermissionNotBetween(Integer value1, Integer value2) {
            addCriterion("PERMISSION not between", value1, value2, "permission");
            return (Criteria) this;
        }

        public Criteria andRolePermissionStateIsNull() {
            addCriterion("ROLE_PERMISSION_STATE is null");
            return (Criteria) this;
        }

        public Criteria andRolePermissionStateIsNotNull() {
            addCriterion("ROLE_PERMISSION_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andRolePermissionStateEqualTo(String value) {
            addCriterion("ROLE_PERMISSION_STATE =", value, "rolePermissionState");
            return (Criteria) this;
        }

        public Criteria andRolePermissionStateNotEqualTo(String value) {
            addCriterion("ROLE_PERMISSION_STATE <>", value, "rolePermissionState");
            return (Criteria) this;
        }

        public Criteria andRolePermissionStateGreaterThan(String value) {
            addCriterion("ROLE_PERMISSION_STATE >", value, "rolePermissionState");
            return (Criteria) this;
        }

        public Criteria andRolePermissionStateGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_PERMISSION_STATE >=", value, "rolePermissionState");
            return (Criteria) this;
        }

        public Criteria andRolePermissionStateLessThan(String value) {
            addCriterion("ROLE_PERMISSION_STATE <", value, "rolePermissionState");
            return (Criteria) this;
        }

        public Criteria andRolePermissionStateLessThanOrEqualTo(String value) {
            addCriterion("ROLE_PERMISSION_STATE <=", value, "rolePermissionState");
            return (Criteria) this;
        }

        public Criteria andRolePermissionStateLike(String value) {
            addCriterion("ROLE_PERMISSION_STATE like", value, "rolePermissionState");
            return (Criteria) this;
        }

        public Criteria andRolePermissionStateNotLike(String value) {
            addCriterion("ROLE_PERMISSION_STATE not like", value, "rolePermissionState");
            return (Criteria) this;
        }

        public Criteria andRolePermissionStateIn(List<String> values) {
            addCriterion("ROLE_PERMISSION_STATE in", values, "rolePermissionState");
            return (Criteria) this;
        }

        public Criteria andRolePermissionStateNotIn(List<String> values) {
            addCriterion("ROLE_PERMISSION_STATE not in", values, "rolePermissionState");
            return (Criteria) this;
        }

        public Criteria andRolePermissionStateBetween(String value1, String value2) {
            addCriterion("ROLE_PERMISSION_STATE between", value1, value2, "rolePermissionState");
            return (Criteria) this;
        }

        public Criteria andRolePermissionStateNotBetween(String value1, String value2) {
            addCriterion("ROLE_PERMISSION_STATE not between", value1, value2, "rolePermissionState");
            return (Criteria) this;
        }

        public Criteria andRolePermissionUpdatetimeIsNull() {
            addCriterion("ROLE_PERMISSION_UPDATETIME is null");
            return (Criteria) this;
        }

        public Criteria andRolePermissionUpdatetimeIsNotNull() {
            addCriterion("ROLE_PERMISSION_UPDATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andRolePermissionUpdatetimeEqualTo(Date value) {
            addCriterion("ROLE_PERMISSION_UPDATETIME =", value, "rolePermissionUpdatetime");
            return (Criteria) this;
        }

        public Criteria andRolePermissionUpdatetimeNotEqualTo(Date value) {
            addCriterion("ROLE_PERMISSION_UPDATETIME <>", value, "rolePermissionUpdatetime");
            return (Criteria) this;
        }

        public Criteria andRolePermissionUpdatetimeGreaterThan(Date value) {
            addCriterion("ROLE_PERMISSION_UPDATETIME >", value, "rolePermissionUpdatetime");
            return (Criteria) this;
        }

        public Criteria andRolePermissionUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ROLE_PERMISSION_UPDATETIME >=", value, "rolePermissionUpdatetime");
            return (Criteria) this;
        }

        public Criteria andRolePermissionUpdatetimeLessThan(Date value) {
            addCriterion("ROLE_PERMISSION_UPDATETIME <", value, "rolePermissionUpdatetime");
            return (Criteria) this;
        }

        public Criteria andRolePermissionUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("ROLE_PERMISSION_UPDATETIME <=", value, "rolePermissionUpdatetime");
            return (Criteria) this;
        }

        public Criteria andRolePermissionUpdatetimeIn(List<Date> values) {
            addCriterion("ROLE_PERMISSION_UPDATETIME in", values, "rolePermissionUpdatetime");
            return (Criteria) this;
        }

        public Criteria andRolePermissionUpdatetimeNotIn(List<Date> values) {
            addCriterion("ROLE_PERMISSION_UPDATETIME not in", values, "rolePermissionUpdatetime");
            return (Criteria) this;
        }

        public Criteria andRolePermissionUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("ROLE_PERMISSION_UPDATETIME between", value1, value2, "rolePermissionUpdatetime");
            return (Criteria) this;
        }

        public Criteria andRolePermissionUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("ROLE_PERMISSION_UPDATETIME not between", value1, value2, "rolePermissionUpdatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table role_permission_relation
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 17 17:17:22 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table role_permission_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}