package com.qsy.demo.oa.shiro.entity;

import java.util.Date;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_ID
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_NAME
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_DESC
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    private String permissionDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_STATE
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    private String permissionState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.PERMISSION_CREATEDATE
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    private Date permissionCreatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PERMISSION_ID
     *
     * @return the value of permission.PERMISSION_ID
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PERMISSION_ID
     *
     * @param permissionId the value for permission.PERMISSION_ID
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PERMISSION_NAME
     *
     * @return the value of permission.PERMISSION_NAME
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PERMISSION_NAME
     *
     * @param permissionName the value for permission.PERMISSION_NAME
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PERMISSION_DESC
     *
     * @return the value of permission.PERMISSION_DESC
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public String getPermissionDesc() {
        return permissionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PERMISSION_DESC
     *
     * @param permissionDesc the value for permission.PERMISSION_DESC
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public void setPermissionDesc(String permissionDesc) {
        this.permissionDesc = permissionDesc == null ? null : permissionDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PERMISSION_STATE
     *
     * @return the value of permission.PERMISSION_STATE
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public String getPermissionState() {
        return permissionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PERMISSION_STATE
     *
     * @param permissionState the value for permission.PERMISSION_STATE
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public void setPermissionState(String permissionState) {
        this.permissionState = permissionState == null ? null : permissionState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.PERMISSION_CREATEDATE
     *
     * @return the value of permission.PERMISSION_CREATEDATE
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public Date getPermissionCreatedate() {
        return permissionCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.PERMISSION_CREATEDATE
     *
     * @param permissionCreatedate the value for permission.PERMISSION_CREATEDATE
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public void setPermissionCreatedate(Date permissionCreatedate) {
        this.permissionCreatedate = permissionCreatedate;
    }
}