package com.qsy.demo.oa.pojo.mapper;

import com.qsy.demo.oa.pojo.GoodsSortRelation;
import com.qsy.demo.oa.pojo.GoodsSortRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsSortRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    long countByExample(GoodsSortRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int deleteByExample(GoodsSortRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int deleteByPrimaryKey(Integer goodsSortId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int insert(GoodsSortRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int insertSelective(GoodsSortRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    List<GoodsSortRelation> selectByExample(GoodsSortRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    GoodsSortRelation selectByPrimaryKey(Integer goodsSortId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") GoodsSortRelation record, @Param("example") GoodsSortRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int updateByExample(@Param("record") GoodsSortRelation record, @Param("example") GoodsSortRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsSortRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sort_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int updateByPrimaryKey(GoodsSortRelation record);
}