package com.qsy.demo.oa.pojo.mapper;

import com.qsy.demo.oa.pojo.UserRoleRelation;
import com.qsy.demo.oa.pojo.UserRoleRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    long countByExample(UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int deleteByExample(UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int deleteByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int insert(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int insertSelective(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    List<UserRoleRelation> selectByExample(UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    UserRoleRelation selectByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserRoleRelation record, @Param("example") UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int updateByExample(@Param("record") UserRoleRelation record, @Param("example") UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int updateByPrimaryKeySelective(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relation
     *
     * @mbg.generated Tue Apr 17 17:17:22 CST 2018
     */
    int updateByPrimaryKey(UserRoleRelation record);
}