package com.qsy.demo.oa.shiro.entity;

public class SortInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort_info.SORT_ID
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    private Integer sortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort_info.SORT_NAME
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    private String sortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort_info.SORT_DESC
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    private String sortDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort_info.SORT_PARENT
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    private Integer sortParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort_info.SORT_STATE
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    private String sortState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort_info.SORT_ID
     *
     * @return the value of sort_info.SORT_ID
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort_info.SORT_ID
     *
     * @param sortId the value for sort_info.SORT_ID
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort_info.SORT_NAME
     *
     * @return the value of sort_info.SORT_NAME
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public String getSortName() {
        return sortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort_info.SORT_NAME
     *
     * @param sortName the value for sort_info.SORT_NAME
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public void setSortName(String sortName) {
        this.sortName = sortName == null ? null : sortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort_info.SORT_DESC
     *
     * @return the value of sort_info.SORT_DESC
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public String getSortDesc() {
        return sortDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort_info.SORT_DESC
     *
     * @param sortDesc the value for sort_info.SORT_DESC
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public void setSortDesc(String sortDesc) {
        this.sortDesc = sortDesc == null ? null : sortDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort_info.SORT_PARENT
     *
     * @return the value of sort_info.SORT_PARENT
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public Integer getSortParent() {
        return sortParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort_info.SORT_PARENT
     *
     * @param sortParent the value for sort_info.SORT_PARENT
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public void setSortParent(Integer sortParent) {
        this.sortParent = sortParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort_info.SORT_STATE
     *
     * @return the value of sort_info.SORT_STATE
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public String getSortState() {
        return sortState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort_info.SORT_STATE
     *
     * @param sortState the value for sort_info.SORT_STATE
     *
     * @mbg.generated Fri Jan 26 14:29:03 CST 2018
     */
    public void setSortState(String sortState) {
        this.sortState = sortState == null ? null : sortState.trim();
    }
}